### PR TITLE
Added /home command

### PR DESCRIPTION
**Pull request by SeqSEE**
This replicates user function of /home command with Essentials.

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
`This replicates user function of /home command with Essentials.`
No it doesn't :(

It creates a new, vaguely similar command, that will be very confusing to end users.

**Comment by SeqSEE** [comment]
Would it be better to make 3 commands
home, sethome, and delhome like Essentials actually has?

**Comment by mcmonkey4eva** [comment]
Yup. Ideally with support for multiple homes.

**Comment by Fortifier42** [comment]
Just like my dCommander homes ;)

**Pull request closed without merging**
